Traceback (most recent call last):
  File "/Users/yewang/.local/pipx/venvs/jupyter-book/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/yewang/.local/pipx/venvs/jupyter-book/lib/python3.9/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/yewang/.local/pipx/venvs/jupyter-book/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/yewang/.pyenv/versions/3.9.15/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/yewang/.local/pipx/venvs/jupyter-book/lib/python3.9/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/yewang/.local/pipx/venvs/jupyter-book/lib/python3.9/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/yewang/.local/pipx/venvs/jupyter-book/lib/python3.9/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# 生成示例预测结果
y_true = [0, 1, 1, 0, 1, 0, 1, 1, 0, 0]
y_pred = [0, 1, 0, 0, 1, 1, 1, 0, 0, 0]

# 计算评估指标
accuracy = accuracy_score(y_true, y_pred)
precision = precision_score(y_true, y_pred)
recall = recall_score(y_true, y_pred)
f1 = f1_score(y_true, y_pred)

print(f'准确率: {accuracy}')
print(f'精确率: {precision}')
print(f'召回率: {recall}')
print(f'F1 分数: {f1}')
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 1[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01msklearn[39;00m[38;5;21;01m.[39;00m[38;5;21;01mmetrics[39;00m [38;5;28;01mimport[39;00m accuracy_score, precision_score, recall_score, f1_score
[1;32m      3[0m [38;5;66;03m# 生成示例预测结果[39;00m
[1;32m      4[0m y_true [38;5;241m=[39m [[38;5;241m0[39m, [38;5;241m1[39m, [38;5;241m1[39m, [38;5;241m0[39m, [38;5;241m1[39m, [38;5;241m0[39m, [38;5;241m1[39m, [38;5;241m1[39m, [38;5;241m0[39m, [38;5;241m0[39m]

[0;31mModuleNotFoundError[0m: No module named 'sklearn'

