Traceback (most recent call last):
  File "/Users/yewang/miniforge3/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/yewang/miniforge3/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/yewang/miniforge3/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/yewang/miniforge3/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/yewang/miniforge3/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/yewang/miniforge3/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/yewang/miniforge3/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from sklearn.ensemble import RandomForestClassifier

# 训练随机森林模型
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X, y)

# 输出特征重要性
importances = rf.feature_importances_
print('特征重要性:', importances)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[1], line 5[0m
[1;32m      3[0m [38;5;66;03m# 训练随机森林模型[39;00m
[1;32m      4[0m rf [38;5;241m=[39m RandomForestClassifier(n_estimators[38;5;241m=[39m[38;5;241m100[39m, random_state[38;5;241m=[39m[38;5;241m42[39m)
[0;32m----> 5[0m rf[38;5;241m.[39mfit([43mX[49m, y)
[1;32m      7[0m [38;5;66;03m# 输出特征重要性[39;00m
[1;32m      8[0m importances [38;5;241m=[39m rf[38;5;241m.[39mfeature_importances_

[0;31mNameError[0m: name 'X' is not defined

